spring.datasource.url=jdbc:mysql://localhost:3306/food_delivery_platform_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456

# Cấu hình hibernate (tự động cập nhật bảng từ java entity)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080